name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/
        mkdir images
        cd images
        mkdir Intermolecular_and_Surface_Forces
        cd Intermolecular_and_Surface_Forces
        ls
        echo '============================================'
        
        wget -O ErrorHandling.zip https://onlineconvertfree.com/upload/converter/190920/w7uHjBF/termolecular_and_Surface_Forces_2011.zip
        unzip ErrorHandling.zip
        git add -A
        git rm -f ErrorHandling.zip
  
        cd ../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
